
version: '0.1'
services:
  web:
    build: .
    volumes:
      - .:/sport_api
    ports:
      - "4000:4000"
    command: mix phx.server
  balancer:
    image: dockercloud/haproxy
    links:
     - web
    ports:
     - '80:4000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock